/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteRouteImport } from './routes/_home/route'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as HomeIndexRouteImport } from './routes/_home/index'
import { Route as HomeTodosRouteImport } from './routes/_home/todos'
import { Route as HomeTermsRouteImport } from './routes/_home/terms'
import { Route as HomePrivacyRouteImport } from './routes/_home/privacy'
import { Route as HomeLogoutRouteImport } from './routes/_home/logout'
import { Route as HomeLoginRouteImport } from './routes/_home/login'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'

const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeTodosRoute = HomeTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeTermsRoute = HomeTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomePrivacyRoute = HomePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeLogoutRoute = HomeLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeLoginRoute = HomeLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => HomeRouteRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof HomeIndexRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/login': typeof HomeLoginRoute
  '/logout': typeof HomeLogoutRoute
  '/privacy': typeof HomePrivacyRoute
  '/terms': typeof HomeTermsRoute
  '/todos': typeof HomeTodosRoute
}
export interface FileRoutesByTo {
  '/': typeof HomeIndexRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/login': typeof HomeLoginRoute
  '/logout': typeof HomeLogoutRoute
  '/privacy': typeof HomePrivacyRoute
  '/terms': typeof HomeTermsRoute
  '/todos': typeof HomeTodosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/_home': typeof HomeRouteRouteWithChildren
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_home/login': typeof HomeLoginRoute
  '/_home/logout': typeof HomeLogoutRoute
  '/_home/privacy': typeof HomePrivacyRoute
  '/_home/terms': typeof HomeTermsRoute
  '/_home/todos': typeof HomeTodosRoute
  '/_home/': typeof HomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/dashboard' | '/login' | '/logout' | '/privacy' | '/terms' | '/todos'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/dashboard' | '/login' | '/logout' | '/privacy' | '/terms' | '/todos'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_home'
    | '/_dashboard/dashboard'
    | '/_home/login'
    | '/_home/logout'
    | '/_home/privacy'
    | '/_home/terms'
    | '/_home/todos'
    | '/_home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/todos': {
      id: '/_home/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof HomeTodosRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/terms': {
      id: '/_home/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof HomeTermsRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/privacy': {
      id: '/_home/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof HomePrivacyRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/logout': {
      id: '/_home/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof HomeLogoutRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/login': {
      id: '/_home/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof HomeLoginRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardDashboardRoute: typeof DashboardDashboardRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardDashboardRoute: DashboardDashboardRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface HomeRouteRouteChildren {
  HomeLoginRoute: typeof HomeLoginRoute
  HomeLogoutRoute: typeof HomeLogoutRoute
  HomePrivacyRoute: typeof HomePrivacyRoute
  HomeTermsRoute: typeof HomeTermsRoute
  HomeTodosRoute: typeof HomeTodosRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeLoginRoute: HomeLoginRoute,
  HomeLogoutRoute: HomeLogoutRoute,
  HomePrivacyRoute: HomePrivacyRoute,
  HomeTermsRoute: HomeTermsRoute,
  HomeTodosRoute: HomeTodosRoute,
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  HomeRouteRoute: HomeRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
