/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteRouteImport } from './routes/_home/route'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as HomeIndexRouteImport } from './routes/_home/index'
import { Route as HomeTodosRouteImport } from './routes/_home/todos'
import { Route as HomeTermsRouteImport } from './routes/_home/terms'
import { Route as HomePrivacyRouteImport } from './routes/_home/privacy'
import { Route as HomeLogoutRouteImport } from './routes/_home/logout'
import { Route as DashboardDashboardIndexRouteImport } from './routes/_dashboard/dashboard/index'
import { Route as DashboardDashboardSettingsRouteImport } from './routes/_dashboard/dashboard/settings'
import { Route as DashboardDashboardBucketsRouteImport } from './routes/_dashboard/dashboard/buckets'
import { Route as DashboardDashboardAppsRouteImport } from './routes/_dashboard/dashboard/apps'

const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeTodosRoute = HomeTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeTermsRoute = HomeTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomePrivacyRoute = HomePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeLogoutRoute = HomeLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => HomeRouteRoute,
} as any)
const DashboardDashboardIndexRoute = DashboardDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDashboardSettingsRoute =
  DashboardDashboardSettingsRouteImport.update({
    id: '/dashboard/settings',
    path: '/dashboard/settings',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardDashboardBucketsRoute =
  DashboardDashboardBucketsRouteImport.update({
    id: '/dashboard/buckets',
    path: '/dashboard/buckets',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardDashboardAppsRoute = DashboardDashboardAppsRouteImport.update({
  id: '/dashboard/apps',
  path: '/dashboard/apps',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof HomeIndexRoute
  '/logout': typeof HomeLogoutRoute
  '/privacy': typeof HomePrivacyRoute
  '/terms': typeof HomeTermsRoute
  '/todos': typeof HomeTodosRoute
  '/dashboard/apps': typeof DashboardDashboardAppsRoute
  '/dashboard/buckets': typeof DashboardDashboardBucketsRoute
  '/dashboard/settings': typeof DashboardDashboardSettingsRoute
  '/dashboard/': typeof DashboardDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof HomeIndexRoute
  '/logout': typeof HomeLogoutRoute
  '/privacy': typeof HomePrivacyRoute
  '/terms': typeof HomeTermsRoute
  '/todos': typeof HomeTodosRoute
  '/dashboard/apps': typeof DashboardDashboardAppsRoute
  '/dashboard/buckets': typeof DashboardDashboardBucketsRoute
  '/dashboard/settings': typeof DashboardDashboardSettingsRoute
  '/dashboard': typeof DashboardDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/_home': typeof HomeRouteRouteWithChildren
  '/_home/logout': typeof HomeLogoutRoute
  '/_home/privacy': typeof HomePrivacyRoute
  '/_home/terms': typeof HomeTermsRoute
  '/_home/todos': typeof HomeTodosRoute
  '/_home/': typeof HomeIndexRoute
  '/_dashboard/dashboard/apps': typeof DashboardDashboardAppsRoute
  '/_dashboard/dashboard/buckets': typeof DashboardDashboardBucketsRoute
  '/_dashboard/dashboard/settings': typeof DashboardDashboardSettingsRoute
  '/_dashboard/dashboard/': typeof DashboardDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logout'
    | '/privacy'
    | '/terms'
    | '/todos'
    | '/dashboard/apps'
    | '/dashboard/buckets'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logout'
    | '/privacy'
    | '/terms'
    | '/todos'
    | '/dashboard/apps'
    | '/dashboard/buckets'
    | '/dashboard/settings'
    | '/dashboard'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_home'
    | '/_home/logout'
    | '/_home/privacy'
    | '/_home/terms'
    | '/_home/todos'
    | '/_home/'
    | '/_dashboard/dashboard/apps'
    | '/_dashboard/dashboard/buckets'
    | '/_dashboard/dashboard/settings'
    | '/_dashboard/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/todos': {
      id: '/_home/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof HomeTodosRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/terms': {
      id: '/_home/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof HomeTermsRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/privacy': {
      id: '/_home/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof HomePrivacyRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/logout': {
      id: '/_home/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof HomeLogoutRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_dashboard/dashboard/': {
      id: '/_dashboard/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardDashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/dashboard/settings': {
      id: '/_dashboard/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardDashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/dashboard/buckets': {
      id: '/_dashboard/dashboard/buckets'
      path: '/dashboard/buckets'
      fullPath: '/dashboard/buckets'
      preLoaderRoute: typeof DashboardDashboardBucketsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/dashboard/apps': {
      id: '/_dashboard/dashboard/apps'
      path: '/dashboard/apps'
      fullPath: '/dashboard/apps'
      preLoaderRoute: typeof DashboardDashboardAppsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardDashboardAppsRoute: typeof DashboardDashboardAppsRoute
  DashboardDashboardBucketsRoute: typeof DashboardDashboardBucketsRoute
  DashboardDashboardSettingsRoute: typeof DashboardDashboardSettingsRoute
  DashboardDashboardIndexRoute: typeof DashboardDashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardDashboardAppsRoute: DashboardDashboardAppsRoute,
  DashboardDashboardBucketsRoute: DashboardDashboardBucketsRoute,
  DashboardDashboardSettingsRoute: DashboardDashboardSettingsRoute,
  DashboardDashboardIndexRoute: DashboardDashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface HomeRouteRouteChildren {
  HomeLogoutRoute: typeof HomeLogoutRoute
  HomePrivacyRoute: typeof HomePrivacyRoute
  HomeTermsRoute: typeof HomeTermsRoute
  HomeTodosRoute: typeof HomeTodosRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeLogoutRoute: HomeLogoutRoute,
  HomePrivacyRoute: HomePrivacyRoute,
  HomeTermsRoute: HomeTermsRoute,
  HomeTodosRoute: HomeTodosRoute,
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  HomeRouteRoute: HomeRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
